[package]
name = "rmace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
arrayvec = "0.7.6"
clap = { version = "4.5.4", features = ["derive"] }
nom = "7.1.3"
num_enum = "0.7.3"
paste = "1.0.15"
strum = { version = "0.26", features = ["derive"] }
itertools = "0.13.0"
